### ISSUE TITLE
Project builds with warnings on VS 2015

### ISSUE THREAD

**Issue by masonwheeler** [lxnt/SDL_pnglite#1]
After building SDL_pnglite with Visual Studio 2015, it gives several warnings.  Some of them are for the pnglite library, but some are for the SDL_pnglite code, indicating possible data corruption:

> 1>------ Build started: Project: SDL_pnglite, Configuration: Debug Win32 ------
> 1>  SDL_pnglite.c
> 1>D:\Projects\SDL_pnglite\SDL_pnglite.c(232): warning C4244: '=': conversion from 'Uint64' to 'int', possible loss of data
> 1>D:\Projects\SDL_pnglite\SDL_pnglite.c(293): warning C4244: '=': conversion from 'Uint64' to 'int', possible loss of data
> 1>D:\Projects\SDL_pnglite\SDL_pnglite.c(329): warning C4244: '=': conversion from 'Uint64' to 'int', possible loss of data
> 1>D:\Projects\SDL_pnglite\SDL_pnglite.c(363): warning C4013: 'memcpy' undefined; assuming extern returning int
> 1>D:\Projects\SDL_pnglite\SDL_pnglite.c(631): warning C4013: 'memset' undefined; assuming extern returning int
> 1>  pnglite.c
> 1>D:\Projects\SDL_pnglite\pnglite.c(349): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
> 1>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(205): note: see declaration of 'fopen'
> 1>D:\Projects\SDL_pnglite\pnglite.c(360): warning C4996: 'fopen': This function or variable may be unsafe. Consider using fopen_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.
> 1>  C:\Program Files (x86)\Windows Kits\10\Include\10.0.10150.0\ucrt\stdio.h(205): note: see declaration of 'fopen'
> 1>  Generating Code...
> 1>  SDL_pnglite.vcxproj -> D:\Projects\SDL_pnglite\bin\Debug\SDL_pnglite.lib
> ========== Build: 1 succeeded, 0 failed, 1 up-to-date, 0 skipped ==========

**Comment by masonwheeler** [comment]
That fixes the memcpy and memset warnings, but the previous ones now warn "conversion from 'Uint64' to 'Uint32', possible loss of data".

**Comment by lxnt** [comment]
Fixed that, and a load of other win32-specific stuff too.
